[build]
publish = "out"
command = "npm run export"

[context.production]
  environment = { SANITY_PROJECT_ID = "9vzhtemc", SANITY_DATASET = "production", STACKBIT_PROJECT_ID = "", WIDGET_URL = "https://widget.stackbit.com/init.js" }

[context.staging]
  environment = { SANITY_PROJECT_ID = "9vzhtemc", SANITY_DATASET = "staging", STACKBIT_PROJECT_ID = "", WIDGET_URL = "https://staging.widget.stackbit.com/init.js" }
